name: .NET Core

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet run
      working-directory: ./build
      env:
        NUGET_ORG_API_KEY: ${{secrets.NUGET_ORG_API_KEY}}
        CLIENTID: ${{secrets.CLIENT_ID}}
        CLIENTSECRET: ${{secrets.CLIENT_SECRET}}
        VAULTURL: ${{secrets.VAULT_URL}}
        VERSION_PREFIX: "1.0"
